module.exports = {
    apps: [
        {
            name: 'api-gateway',
            script: 'dist/apps/api-gateway/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/api-gateway-error.log',
            out_file: './logs/api-gateway-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'accounts-service',
            script: 'dist/apps/accounts-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/accounts-service-error.log',
            out_file: './logs/accounts-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'users-service',
            script: 'dist/apps/users-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/users-service-error.log',
            out_file: './logs/users-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'auth-service',
            script: 'dist/apps/auth-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/auth-service-error.log',
            out_file: './logs/auth-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'notification-service',
            script: 'dist/apps/notification-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/notification-service-error.log',
            out_file: './logs/notification-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'transactions-service',
            script: 'dist/apps/transactions-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/transactions-service-error.log',
            out_file: './logs/transactions-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'customer-service',
            script: 'dist/apps/customer-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/customer-service-error.log',
            out_file: './logs/customer-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
        {
            name: 'migration-service',
            script: 'dist/apps/migration-service/main.js',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            error_file: './logs/migration-service-error.log',
            out_file: './logs/migration-service-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
        },
    ],
};
