export const MESSAGE_PATTERNS = {
  accounts: {
    CREATE: 'accounts.create',
    CREATE_WITH_CUSTOMER: 'accounts.create_with_customer',
    FIND_ALL: 'accounts.find_all',
    FIND_WITH_CUSTOMERS: 'accounts.find_with_customers',
    FIND_ONE: 'accounts.find_one',
    UPDATE: 'accounts.update',
    UPDATE_STATUS: 'accounts.update_status',
    DELETE: 'accounts.delete',
    GET_BALANCE: 'accounts.get_balance',
  },
  users: {
    CREATE: 'users.create',
    FIND_ALL: 'users.find_all',
    FIND_ONE: 'users.find_one',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
    FIND_BY_EMAIL_WITH_PASSWORD: 'users.find_by_email_with_password',
  },
  auth: {
    CREATE: 'auth.create',
    FIND_ALL: 'auth.find_all',
    FIND_ONE: 'auth.find_one',
    UPDATE: 'auth.update',
    DELETE: 'auth.delete',
    LOGIN: 'auth.login',
  },
  migration: {
    CREATE: 'migration.create',
    FIND_ALL: 'migration.find_all',
    FIND_ONE: 'migration.find_one',
    UPDATE: 'migration.update',
    DELETE: 'migration.delete',
  },
  customer: {
    CREATE: 'customer.create',
    FIND_ALL: 'customer.find_all',
    FIND_ONE: 'customer.find_one',
    UPDATE: 'customer.update',
    DELETE: 'customer.delete',
    GET_KYC_STATUS: 'customer.get_kyc_status',
    GET_STATS: 'customer.get_stats',
  },
  transactions: {
    CREATE: 'transactions.create',
    DEPOSIT: 'transactions.deposit',
    WITHDRAW: 'transactions.withdraw',
    TRANSFER: 'transactions.transfer',
    FIND_ALL: 'transactions.find_all', // acts as history
    FIND_ONE: 'transactions.find_one',
    UPDATE: 'transactions.update',
    DELETE: 'transactions.delete',
    GET_STATS: 'transactions.get_stats',
  },
  notification: {
    CREATE: 'notification.create',
    FIND_ALL: 'notification.find_all',
    FIND_ONE: 'notification.find_one',
    UPDATE: 'notification.update',
    DELETE: 'notification.delete',
  },
  BRANCH: {
    CREATE: 'branch.create',
    FIND_ALL: 'branch.find_all',
    FIND_ONE: 'branch.find_one',
    UPDATE: 'branch.update',
    DELETE: 'branch.delete',
  },
};
