export const MESSAGE_PATTERNS = {
  accounts: {
    CREATE: 'accounts.create',
    FIND_ALL: 'accounts.find_all',
    FIND_ONE: 'accounts.find_one',
    UPDATE: 'accounts.update',
    DELETE: 'accounts.delete',
  },
  users: {
    CREATE: 'users.create',
    FIND_ALL: 'users.find_all',
    FIND_ONE: 'users.find_one',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
    FIND_BY_EMAIL_WITH_PASSWORD: 'users.find_by_email_with_password',
  },
  auth: {
    CREATE: 'auth.create',
    FIND_ALL: 'auth.find_all',
    FIND_ONE: 'auth.find_one',
    UPDATE: 'auth.update',
    DELETE: 'auth.delete',
    LOGIN: 'auth.login',
  },
  migration: {
    CREATE: 'migration.create',
    FIND_ALL: 'migration.find_all',
    FIND_ONE: 'migration.find_one',
    UPDATE: 'migration.update',
    DELETE: 'migration.delete',
  },
  customer: {
    CREATE: 'customer.create',
    FIND_ALL: 'customer.find_all',
    FIND_ONE: 'customer.find_one',
    UPDATE: 'customer.update',
    DELETE: 'customer.delete',
  },
  transactions: {
    CREATE: 'transactions.create',
    FIND_ALL: 'transactions.find_all',
    FIND_ONE: 'transactions.find_one',
    UPDATE: 'transactions.update',
    DELETE: 'transactions.delete',
  },
  notification: {
    CREATE: 'notification.create',
    FIND_ALL: 'notification.find_all',
    FIND_ONE: 'notification.find_one',
    UPDATE: 'notification.update',
    DELETE: 'notification.delete',
  },
};
